#!/usr/bin/env python3
"""
build.py – Parser + static HTML renderer for pedagogy-hub.html
All accordion HTML is generated by Python and injected into template.html.
JavaScript only handles interactivity (toggle, view switch, tech filter).
"""

import json, re, base64, os, html as html_mod
from pathlib import Path
from docx import Document
from docx.oxml.ns import qn
from lxml import etree
from PIL import Image
import io

SCRIPT_DIR = Path(os.path.abspath(__file__)).parent if '__file__' in dir() else Path('/home/claude')
UNNAMED = '__UNNAMED__'

# ── unicode cleanup ────────────────────────────────────────────────────────
UNICODE_MAP = {
    '\u2018':"'",'\u2019':"'",'\u201c':'"','\u201d':'"',
    '\u2013':'-','\u2014':'--','\u2026':'...','\u00a0':' ',
    '\uf0b7':'','\uf0a7':'','\uf020':'',
}
def clean(text):
    if not text: return ''
    for src,dst in UNICODE_MAP.items(): text=text.replace(src,dst)
    text=re.sub(r'[\ue000-\uf8ff]','',text)
    text=re.sub(r'\s+',' ',text)
    return text.strip()

def esc(s): return html_mod.escape(str(s or ''))
def para_text(p): return clean(''.join(run.text or '' for run in p.runs))

def para_html(p, rels=None):
    """Return paragraph content as HTML, with external hyperlinks as <a> tags.
    Uses python-docx run objects for correct xml:space handling."""
    import html as html_mod
    from docx.oxml.ns import qn as _qn
    parts = []
    for child in p._element:
        tag = child.tag.split('}')[-1]
        if tag == 'r':
            # Use python-docx to extract run text (handles xml:space correctly)
            from docx.text.run import Run as DocxRun
            run = DocxRun(child, p)
            text = run.text or ''
            if text:
                parts.append(html_mod.escape(text))
        elif tag == 'hyperlink':
            rId = child.get(_qn('r:id'))
            # Extract text from all runs inside hyperlink
            from docx.text.run import Run as DocxRun
            hl_text = ''
            for r_child in child:
                if r_child.tag.split('}')[-1] == 'r':
                    run = DocxRun(r_child, p)
                    hl_text += run.text or ''
            url = rels.get(rId) if rels and rId else None
            if url and url not in ('0', '') and url.startswith('http'):
                parts.append(f'<a href="{html_mod.escape(url)}" target="_blank" rel="noopener">{html_mod.escape(hl_text)}</a>')
            else:
                parts.append(html_mod.escape(hl_text))
    return ''.join(parts)

def build_rels(doc):
    """Build rId -> url mapping from document relationships."""
    rels = {}
    for rel in doc.part.rels.values():
        rels[rel.rId] = rel.target_ref
    return rels
def is_tech(p): return bool(re.match(r'^\(Tech\)',para_text(p),re.IGNORECASE))
def strip_tech(t): return re.sub(r'^\(Tech\)\s*','',t,flags=re.IGNORECASE).strip()
def para_style(p): return (p.style.name or '').strip()
def is_heading(p): return any(s in para_style(p) for s in ('Title','Heading'))
def has_image(p): return bool(p._element.findall('.//' + qn('a:blip')))

def compress_image(image_bytes, max_width=900, quality=72):
    try:
        img = Image.open(io.BytesIO(image_bytes))
        if img.mode in ('RGBA','P','LA'):
            bg = Image.new('RGB', img.size, (255,255,255))
            img2 = img.convert('RGBA') if img.mode=='P' else img
            bg.paste(img2, mask=img2.split()[-1])
            img = bg
        elif img.mode != 'RGB': img = img.convert('RGB')
        if img.width > max_width:
            ratio = max_width/img.width
            img = img.resize((max_width,int(img.height*ratio)), Image.LANCZOS)
        buf = io.BytesIO()
        img.save(buf, format='JPEG', quality=quality, optimize=True)
        return buf.getvalue(), 'image/jpeg'
    except: return image_bytes, ('image/png' if image_bytes[:4]==b'\x89PNG' else 'image/jpeg')

def extract_image_b64(p, docx_path):
    blips = p._element.findall('.//' + qn('a:blip'))
    if not blips: return None
    rId = blips[0].get(qn('r:embed'))
    if not rId: return None
    doc2 = Document(docx_path)
    for rel in doc2.part.rels.values():
        if rel.reltype.endswith('/image') and rel.rId == rId:
            image_bytes = rel.target_part.blob
            if len(image_bytes) > 100*1024:
                image_bytes, mime = compress_image(image_bytes)
            else:
                mime = 'image/png' if image_bytes[:4]==b'\x89PNG' else 'image/jpeg'
            b64 = base64.b64encode(image_bytes).decode('utf-8')
            return f'data:{mime};base64,{b64}'
    return None

# ── numbering lookup ───────────────────────────────────────────────────────
def build_numbering_lookup(doc):
    numbering_part = None
    for rel in doc.part.rels.values():
        if 'numbering' in rel.reltype: numbering_part = rel.target_part; break
    if not numbering_part: return {}, {}
    ns = 'http://schemas.openxmlformats.org/wordprocessingml/2006/main'
    root = etree.fromstring(numbering_part.blob)
    abstract = {}
    for abNum in root.findall(f'{{{ns}}}abstractNum'):
        abId = abNum.get(f'{{{ns}}}abstractNumId'); abstract[abId] = {}
        for lvl in abNum.findall(f'{{{ns}}}lvl'):
            ilvl = lvl.get(f'{{{ns}}}ilvl')
            lvlText = lvl.find(f'{{{ns}}}lvlText')
            abstract[abId][ilvl] = lvlText.get(f'{{{ns}}}val','') if lvlText is not None else ''
    num_to_abstract = {}
    for num in root.findall(f'{{{ns}}}num'):
        numId = num.get(f'{{{ns}}}numId')
        abRef = num.find(f'{{{ns}}}abstractNumId')
        if abRef is not None: num_to_abstract[numId] = abRef.get(f'{{{ns}}}val')
    return abstract, num_to_abstract

def get_bullet_level(p, abstract, num_to_abstract):
    numPr = p._element.find('.//' + qn('w:numPr'))
    ilvl_val=0; numId_val=None
    if numPr is not None:
        ilvl_el=numPr.find(qn('w:ilvl')); numId_el=numPr.find(qn('w:numId'))
        if ilvl_el is not None: ilvl_val=int(ilvl_el.get(qn('w:val'),'0'))
        if numId_el is not None: numId_val=numId_el.get(qn('w:val'))
    if ilvl_val>=1: return 1
    if numId_val and numId_val in num_to_abstract:
        abId=num_to_abstract[numId_val]
        if abstract.get(abId,{}).get(str(ilvl_val),'')=='o': return 1
    return 0

def cell_bullets(cell, abstract, num_to_abstract, rels=None):
    bullets=[]
    for p in cell.paragraphs:
        t=para_text(p)
        if not t: continue
        tech=is_tech(p); level=get_bullet_level(p,abstract,num_to_abstract)
        html_text=para_html(p, rels)
        display=strip_tech(html_text) if tech else html_text
        bullets.append({'text':display,'tech':tech,'level':level,'is_html':True})
    return bullets

def cell_plain(cell): return clean(cell.text)

TAG_RE = re.compile(r'^\[([^\]]+)\]')
def parse_aims_cell(cell):
    paras=[clean(p.text) for p in cell.paragraphs if clean(p.text)]
    blocks=[]; current_tag=None; current_lines=[]
    def flush():
        if current_tag is not None: blocks.append({'tag':current_tag,'text':' '.join(current_lines).strip()})
    for para in paras:
        m=TAG_RE.match(para)
        if m:
            flush(); current_tag=m.group(1).strip(); rest=para[m.end():].strip()
            current_lines=[rest] if rest else []
        else:
            if current_tag is not None: current_lines.append(para)
            else: blocks.append({'tag':None,'text':para})
    flush()
    return blocks if blocks else None

def identify_table(tbl):
    if not tbl.rows: return 'unknown'
    first_cell=clean(tbl.rows[0].cells[0].text)
    if len(tbl.rows)==1 and len(tbl.columns)==1 and first_cell.lower().startswith('key question'): return 'key_question'
    headers=[clean(c.text).lower() for c in tbl.rows[0].cells]
    if len(tbl.columns)==2 and headers[0] in ('component',''): return 'ibl_component'
    if any('teacher' in h for h in headers) and any('student' in h for h in headers): return 'phase'
    if any('lower' in h for h in headers) and any('higher' in h for h in headers):
        return 'diff_ibl' if len(tbl.columns)>=6 else 'diff_standard'
    if len(tbl.columns)>=6 and any('more' in h or 'essential' in h for h in headers): return 'diff_ibl'
    return 'unknown'

def parse_phase_table(tbl, abstract, num_to_abstract, rels=None):
    rows=tbl.rows
    if not rows: return None
    col_headers=[cell_plain(c) for c in rows[0].cells]; n_cols=len(col_headers)
    teacher_col=next((i for i,h in enumerate(col_headers) if 'teacher' in h.lower()),1)
    student_col=next((i for i,h in enumerate(col_headers) if 'student' in h.lower()),2)
    aims_col=next((i for i,h in enumerate(col_headers) if any(k in h.lower() for k in ['align','aim','relev'])),n_cols-1 if n_cols>3 else None)
    parsed_rows=[]
    for row in rows[1:]:
        cells=row.cells
        if not cells or not any(cell_plain(c) for c in cells): continue
        # Phase label: Heading 3 = main name, Normal = sub-label
        col0_paras = [(p.style.name or '', para_html(p, rels), para_text(p))
                      for p in cells[0].paragraphs if para_text(p).strip()]
        if col0_paras:
            main = col0_paras[0]
            phase_label = re.sub(r'^\d+\.\s*','', (main[2] if not main[1] else main[2])).strip()
            phase_html_label = main[1] if main[1] else esc(main[2])
            sub_paras = col0_paras[1:]
            phase_sub = ' '.join(p[2] for p in sub_paras).strip()
            phase_sub_html = ' '.join(p[1] for p in sub_paras).strip()
        else:
            phase_label = ''; phase_html_label = ''; phase_sub = ''; phase_sub_html = ''
        teacher_bullets=cell_bullets(cells[teacher_col],abstract,num_to_abstract,rels) if teacher_col<len(cells) else []
        student_bullets=cell_bullets(cells[student_col],abstract,num_to_abstract,rels) if student_col<len(cells) else []
        aims_blocks=parse_aims_cell(cells[aims_col]) if aims_col is not None and aims_col<len(cells) else None
        if phase_label and not teacher_bullets and not student_bullets and not aims_blocks: continue
        parsed_rows.append({'phase':phase_label,'phase_html':phase_html_label,'phase_sub':phase_sub,'phase_sub_html':phase_sub_html,'teacher':teacher_bullets,'student':student_bullets,'aims':aims_blocks})
    return {'col_headers':col_headers,'teacher_col':teacher_col,'student_col':student_col,'aims_col':aims_col,'rows':parsed_rows}

def parse_diff_stage_cell(cell, rels=None):
    """Parse diff table stage column: Heading 3 = main label, Normal = sub-label."""
    paras = [(p.style.name or '', para_html(p, rels), para_text(p))
             for p in cell.paragraphs if para_text(p).strip()]
    if not paras: return '', '', '', ''
    main_html = paras[0][1]; main_plain = paras[0][2]
    sub_paras = paras[1:]
    sub_html = ' '.join(p[1] for p in sub_paras).strip()
    sub_plain = ' '.join(p[2] for p in sub_paras).strip()
    return main_plain, main_html, sub_plain, sub_html

def parse_diff_table_standard(tbl, abstract=None, num_to_abstract=None, rels=None):
    rows=tbl.rows
    if not rows: return {'type':'standard','headers':[],'stages':[],'has_role_col':False}
    headers=[cell_plain(c) for c in rows[0].cells]
    lower_col=next((i for i,h in enumerate(headers) if 'lower' in h.lower()),1)
    higher_col=next((i for i,h in enumerate(headers) if 'higher' in h.lower()),2)
    role_col=next((i for i,h in enumerate(headers) if h.lower()=='role'),None)
    stages=[]
    ab=abstract or {}; nm=num_to_abstract or {}
    for row in rows[1:]:
        cells=row.cells
        if not cells or not any(cell_plain(c) for c in cells): continue
        stage_plain, stage_html, stage_sub, stage_sub_html = parse_diff_stage_cell(cells[0], rels)
        lower_bullets=cell_bullets(cells[lower_col],ab,nm,rels) if lower_col<len(cells) else []
        higher_bullets=cell_bullets(cells[higher_col],ab,nm,rels) if higher_col<len(cells) else []
        role_val=cell_plain(cells[role_col]) if role_col is not None and role_col<len(cells) else None
        if role_col is not None:
            if stage_plain and (not stages or stage_plain!=stages[-1]['stage']):
                stages.append({'stage':stage_plain,'stage_html':stage_html,'stage_sub':stage_sub,'stage_sub_html':stage_sub_html,
                               'teacher_lower':[],'teacher_higher':[],'student_lower':[],'student_higher':[]})
            if stages:
                if role_val and 'teacher' in role_val.lower(): stages[-1]['teacher_lower']=lower_bullets; stages[-1]['teacher_higher']=higher_bullets
                elif role_val and 'student' in role_val.lower(): stages[-1]['student_lower']=lower_bullets; stages[-1]['student_higher']=higher_bullets
        else:
            if stage_plain:
                stages.append({'stage':stage_plain,'stage_html':stage_html,'stage_sub':stage_sub,'stage_sub_html':stage_sub_html,
                               'lower':lower_bullets,'higher':higher_bullets})
            elif stages:
                stages[-1]['lower']=stages[-1].get('lower',[])+lower_bullets
                stages[-1]['higher']=stages[-1].get('higher',[])+higher_bullets
            else:
                stages.append({'stage':UNNAMED,'stage_html':UNNAMED,'stage_sub':'','stage_sub_html':'',
                               'lower':lower_bullets,'higher':higher_bullets})
    return {'type':'standard','headers':headers,'stages':stages,'has_role_col':role_col is not None}

def parse_diff_table_ibl(tbl):
    rows=tbl.rows
    if not rows: return {'type':'ibl_matrix','features':[]}
    features=[]; seen={}
    for row in rows[2:]:
        cells=row.cells
        if len(cells)<6: continue
        fv=clean(cells[0].text); rv=clean(cells[1].text)
        lc=[clean(cells[i].text) for i in range(2,6)]
        if not fv and not rv: continue
        if fv and fv not in seen: seen[fv]=len(features); features.append({'name':fv,'teacher':[],'students':[]})
        fi=seen.get(fv,len(features)-1)
        if fi>=len(features): continue
        if 'teacher' in rv.lower(): features[fi]['teacher']=lc
        elif 'student' in rv.lower(): features[fi]['students']=lc
    return {'type':'ibl_matrix','features':features}

# ── section markers ────────────────────────────────────────────────────────
WHAT_IS_START = lambda tl,st: 'what is' in tl and any(s in st for s in ('Title','Heading','Normal'))
LE_START      = lambda tl,st: any(m in tl for m in ['le facilitated','learning experience (le) in the classroom'])
DIFF_START    = lambda tl,st: 'differentiating' in tl and any(s in st for s in ('Heading','Title','Subtitle'))
WHAT_IS_END   = lambda tl,st: any(m in tl for m in ['le facilitated','learning experience (le) in the classroom','differentiating']) and any(s in st for s in ('Heading','Title'))
LE_END        = lambda tl,st: 'differentiating' in tl and any(s in st for s in ('Heading','Title'))
DIFF_END      = lambda tl,st: False

# ── HTML renderers (Python) ────────────────────────────────────────────────
AIM_CLASSES = {'understand':'understand','appreciate':'appreciate','take action':'action'}
def aim_class(tag):
    t=tag.lower()
    for k,v in AIM_CLASSES.items():
        if t.startswith(k): return v
    return 'understand'

def render_bullets_html(items, show_tech=True):
    if not items: return ''
    visible=[b for b in items if show_tech or not b.get('tech')]
    if not visible: return ''
    def txt(b): return b['text'] if b.get('is_html') else esc(b['text'])
    html='<ul class="bullet-list">'
    i=0
    while i<len(visible):
        b=visible[i]
        badge='<span class="tech-badge">Tech</span> ' if b.get('tech') else ''
        cls=' class="tech-item"' if b.get('tech') else ''
        if b.get('level',0)==0:
            html+=f'<li{cls}>{badge}{txt(b)}'
            subs=[]; j=i+1
            while j<len(visible) and visible[j].get('level',0)>=1: subs.append(visible[j]); j+=1
            if subs:
                html+='<ul>'
                for s in subs:
                    sb='<span class="tech-badge">Tech</span> ' if s.get('tech') else ''
                    sc=' class="tech-item"' if s.get('tech') else ''
                    html+=f'<li{sc}>{sb}{txt(s)}</li>'
                html+='</ul>'; i=j
            else: i+=1
            html+='</li>'
        else:
            html+=f'<li{cls} style="list-style:circle;margin-left:1.1em">{badge}{txt(b)}</li>'; i+=1
    return html+'</ul>'

def render_aims_html(blocks):
    if not blocks: return ''
    out=''
    for b in blocks:
        if not b.get('tag'): out+=f'<div class="aims-block"><span class="aim-text">{esc(b["text"])}</span></div>'; continue
        cls=aim_class(b['tag'])
        text_part=f'<span class="aim-text">{esc(b["text"])}</span>' if b.get('text') else ''
        out+=f'<div class="aims-block"><span class="aim-badge {cls}">{esc(b["tag"])}</span>{text_part}</div>'
    return out

def render_image_html(src, caption=''):
    cap=f'<figcaption>{esc(caption)}</figcaption>' if caption else ''
    return f'<figure class="stream-image"><img src="{src}" alt="Diagram">{cap}</figure>'

def render_what_is_html(items):
    if not items: return ''
    html=''; in_list=False
    def close():
        nonlocal html, in_list
        if in_list: html+='</ul>'; in_list=False
    for item in items:
        if item.get('type')=='image':
            close(); html+=render_image_html(item['src'], item.get('caption',''))
        elif item.get('type')=='subheading':
            close()
            txt=item['text'] if item.get('is_html') else esc(item['text'])
            html+=f'<div class="section-subheading">{txt}</div>'
        elif item.get('type')=='bullet_group':
            close()
            html+='<ul class="what-is-bullets">'
            for b in item.get('items',[]): html+=f'<li>{esc(b["text"])}</li>'
            html+='</ul>'
        elif item.get('type')=='para':
            close()
            txt=item['text'] if item.get('is_html') else esc(item['text'])
            html+=f'<p class="stream-para">{txt}</p>'
        else:
            if not in_list: html+='<ul class="what-is-bullets">'; in_list=True
            cls=' class="sub"' if item.get('level',0)>=1 else ''
            txt=item['text'] if item.get('is_html') else esc(item['text'])
            html+=f'<li{cls}>{txt}</li>'
    close()
    return html

def render_key_question_html(paras):
    if not paras: return ''
    first=paras[0]; colon=first.find(':')
    label=first; rest=[]
    if colon>-1:
        label=first[:colon+1].strip(); after=first[colon+1:].strip()
        rest=[after]+list(paras[1:]) if after else list(paras[1:])
    else: rest=list(paras[1:])
    body=''.join(f'<p>{esc(p)}</p>' for p in rest)
    return f'<div class="key-question"><span class="key-question-label">{esc(label)}</span>{body}</div>'

def render_le_preamble_html(items):
    if not items: return ''
    out=''; in_ul=False
    # wrap consecutive li items in ul
    out=''; in_ul=False
    for item in items:
        if item.get('type') == 'image':
            if in_ul: out+='</ul>'; in_ul=False
            out+=render_image_html(item['src'], item.get('caption',''))
        elif item.get('type') == 'subheading':
            if in_ul: out+='</ul>'; in_ul=False
            txt=item['text'] if item.get('is_html') else esc(item['text'])
            out+=f'<div class="section-subheading">{txt}</div>'
        elif item.get('type') == 'para':
            if in_ul: out+='</ul>'; in_ul=False
            txt=item['text'] if item.get('is_html') else esc(item['text'])
            out+=f'<p class="stream-para">{txt}</p>'
        else:
            cls=' class="sub"' if item.get('level',0)>=1 else ''
            txt=item['text'] if item.get('is_html') else esc(item['text'])
            if not in_ul: out+='<ul>'; in_ul=True
            out+=f'<li{cls}>{txt}</li>'
    if in_ul: out+='</ul>'
    return f'<div class="le-preamble">{out}</div>' if out else ''

def render_phase_table_html(pt, is_ibl=False, key=''):
    if not pt or not pt.get('rows'): return ''
    wclass=' ibl-widths' if is_ibl else ''
    col_classes=['col-phase','col-teacher','col-student','col-aims']
    ths=''.join(f'<th class="{col_classes[i] if i<len(col_classes) else ""}">{esc(h)}</th>' for i,h in enumerate(pt['col_headers']))
    trs=''
    for r in pt['rows']:
        th=render_bullets_html(r.get('teacher',[]))
        st=render_bullets_html(r.get('student',[]))
        aims=render_aims_html(r.get('aims') or [])
        aims_td=f'<td class="aims-cell-td"><div class="cell-scroll">{aims}</div></td>' if r.get('aims') is not None else ''
        phase_html = r.get('phase_html') or esc(r['phase'])
        sub_html = r.get('phase_sub_html') or (esc(r['phase_sub']) if r.get('phase_sub') else '')
        sub_div = f'<div class="phase-sublabel">{sub_html}</div>' if sub_html else ''
        trs+=f'<tr><td class="phase-label">{phase_html}{sub_div}</td><td><div class="cell-scroll">{th}</div></td><td><div class="cell-scroll">{st}</div></td>{aims_td}</tr>'
    return f'<div class="phase-table-wrap"><table class="phase-tbl{wclass}" cellspacing="0"><thead><tr>{ths}</tr></thead><tbody>{trs}</tbody></table></div>'

def render_phase_cards_html(pt):
    if not pt or not pt.get('rows'): return ''
    l2=pt['col_headers'][pt['teacher_col']] if pt['teacher_col']<len(pt['col_headers']) else "Teacher's Role"
    l3=pt['col_headers'][pt['student_col']] if pt['student_col']<len(pt['col_headers']) else "Students' Role"
    cards=''
    for r in pt['rows']:
        th=render_bullets_html(r.get('teacher',[]))
        st=render_bullets_html(r.get('student',[]))
        aims=render_aims_html(r.get('aims') or [])
        t_sec=f'<div class="card-role">{esc(l2)}</div>{th}' if th else ''
        s_sec=f'<div class="card-role">{esc(l3)}</div>{st}' if st else ''
        a_sec=f'<div class="card-aims">{aims}</div>' if aims else ''
        phase_html = r.get('phase_html') or esc(r['phase'])
        sub_html = r.get('phase_sub_html') or (esc(r['phase_sub']) if r.get('phase_sub') else '')
        sub_div = f'<div class="phase-sublabel">{sub_html}</div>' if sub_html else ''
        cards+=f'<div class="phase-card"><h3>{phase_html}</h3>{sub_div}{t_sec}{s_sec}{a_sec}</div>'
    return f'<div class="cards-grid">{cards}</div>'

def has_tech(pt):
    if not pt: return False
    return any(b.get('tech') for r in pt.get('rows',[]) for b in r.get('teacher',[])+r.get('student',[]))

def render_diff_stream_html(stream, first_phase_name='Stage 1'):
    """Render diff section free-flowing: bullets, images, tables in document order."""
    if not stream: return ''
    out = ''
    # collect consecutive bullets into a single <ul>
    bullet_buf = []

    def flush_bullets():
        nonlocal out, bullet_buf
        if not bullet_buf: return
        li = ''
        i = 0
        while i < len(bullet_buf):
            b = bullet_buf[i]
            txt = b['text'] if b.get('is_html') else esc(b['text'])
            if b.get('level', 0) == 0:
                li += f'<li>{txt}'
                subs = []; j = i+1
                while j < len(bullet_buf) and bullet_buf[j].get('level',0) >= 1:
                    subs.append(bullet_buf[j]); j += 1
                if subs:
                    li += '<ul>'
                    for s in subs:
                        st = s['text'] if s.get('is_html') else esc(s['text'])
                        li += f'<li class="sub">{st}</li>'
                    li += '</ul>'; i = j
                else: i += 1
                li += '</li>'
            else:
                li += f'<li class="sub">{txt}</li>'; i += 1
        out += f'<div class="diff-preamble"><ul>{li}</ul></div>'
        bullet_buf = []

    for item in stream:
        if item['type'] == 'bullet':
            bullet_buf.append(item)
        elif item['type'] == 'subheading':
            flush_bullets()
            txt=item['text'] if item.get('is_html') else esc(item['text'])
            out += f'<div class="section-subheading">{txt}</div>'
        elif item['type'] == 'para':
            flush_bullets()
            txt=item['text'] if item.get('is_html') else esc(item['text'])
            out += f'<p class="stream-para">{txt}</p>'
        elif item['type'] == 'image':
            flush_bullets()
            out += render_image_html(item['src'], item.get('caption', ''))
        elif item['type'] == 'table':
            flush_bullets()
            if item['table_type'] == 'diff_ibl':
                out += render_diff_ibl_html(item['data'])
            elif item['table_type'] == 'diff_standard':
                out += render_diff_standard_html(item['data'], first_phase_name)
    flush_bullets()
    return out

def render_diff_preamble_html(items):
    if not items: return ''
    li=''.join(f'<li>{i["text"] if i.get("is_html") else esc(i["text"])}</li>' for i in items)
    return f'<div class="diff-preamble"><ul>{li}</ul></div>'

def render_diff_cell(val):
    """Render a diff cell: list of bullet dicts -> bullet HTML, or plain string."""
    if isinstance(val, list):
        return render_bullets_html(val, show_tech=True) if val else ''
    return esc(str(val)) if val else ''

def render_diff_standard_html(dt, first_phase_name='Stage 1'):
    if not dt or not dt.get('stages'): return ''
    headers=dt['headers']; has_role=dt.get('has_role_col',False)
    ths=''.join(f'<th>{esc(h)}</th>' for h in headers)
    rows=''
    for s in dt['stages']:
        name_html = s.get('stage_html') or esc(s['stage'])
        if s['stage'] == UNNAMED: name_html = esc(first_phase_name)
        sub_html = s.get('stage_sub_html') or (esc(s['stage_sub']) if s.get('stage_sub') else '')
        sub_div = f'<div class="phase-sublabel">{sub_html}</div>' if sub_html else ''
        stage_td = f'{name_html}{sub_div}'
        if has_role:
            rows+=(f'<tr><td class="diff-stage" rowspan="2">{stage_td}</td>'
                   f'<td class="diff-role">Teacher</td>'
                   f'<td>{render_diff_cell(s.get("teacher_lower",""))}</td>'
                   f'<td>{render_diff_cell(s.get("teacher_higher",""))}</td></tr>'
                   f'<tr><td class="diff-role">Students</td>'
                   f'<td>{render_diff_cell(s.get("student_lower",""))}</td>'
                   f'<td>{render_diff_cell(s.get("student_higher",""))}</td></tr>')
        else:
            rows+=(f'<tr><td class="diff-stage">{stage_td}</td>'
                   f'<td>{render_diff_cell(s.get("lower",""))}</td>'
                   f'<td>{render_diff_cell(s.get("higher",""))}</td></tr>')
    return f'<div style="overflow-x:auto"><table class="diff-tbl" cellspacing="0"><thead><tr>{ths}</tr></thead><tbody>{rows}</tbody></table></div>'

def render_diff_ibl_html(dt):
    if not dt or not dt.get('features'): return ''
    rows=''
    for f in dt['features']:
        ts=''.join(f'<td>{esc(c)}</td>' for c in f.get('teacher',[]))
        ss=''.join(f'<td>{esc(c)}</td>' for c in f.get('students',[]))
        rows+=(f'<tr class="trow"><td class="fcell" rowspan="2">{esc(f["name"])}</td>'
               f'<td class="rcell">Teacher</td>{ts}</tr>'
               f'<tr class="srow"><td class="rcell">Students</td>{ss}</tr>')
    return (f'<div style="overflow-x:auto"><table class="ibl-matrix" cellspacing="0">'
            f'<thead><tr><th class="fhdr" rowspan="2">Essential Feature</th>'
            f'<th class="rhdr" rowspan="2">Role</th>'
            f'<th colspan="4">Extent of Guidance from Teacher &#8592; More &nbsp; Less &#8594;</th></tr>'
            f'<tr class="ibl-arrow-row"><th>Highly structured</th><th>Guided</th>'
            f'<th>Structured inquiry</th><th>Open inquiry</th></tr></thead>'
            f'<tbody>{rows}</tbody></table></div>')

# ── parse one doc ──────────────────────────────────────────────────────────
def parse_doc(docx_path, approach_key):
    doc=Document(docx_path); abstract,num_to_abstract=build_numbering_lookup(doc); rels=build_rels(doc)
    body=doc.element.body; data={}

    # What is X? — free-flowing
    what_is=[]; in_wi=False
    for child in body:
        tag=child.tag.split('}')[-1]
        if tag=='p':
            from docx.text.paragraph import Paragraph as DP
            p=DP(child,doc); text=para_text(p); style=para_style(p); tl=text.lower()
            if not in_wi:
                if WHAT_IS_START(tl,style): in_wi=True; continue
            else:
                if WHAT_IS_END(tl,style): break
                if not text and not has_image(p): continue
                if has_image(p):
                    src=extract_image_b64(p,docx_path)
                    if src: what_is.append({'type':'image','src':src,'caption':re.sub(r'^\.\s*','',text).strip()})
                    continue
                if 'Caption' in style:
                    if what_is and what_is[-1].get('type')=='image' and not what_is[-1]['caption']:
                        what_is[-1]['caption']=re.sub(r'^\.\s*','',text).strip()
                    continue
                if 'Heading 3' in style:
                    what_is.append({'type':'subheading','text':para_html(p,rels),'is_html':True})
                    continue
                html_text=para_html(p,rels)
                if 'List Paragraph' in style:
                    level=get_bullet_level(p,abstract,num_to_abstract)
                    what_is.append({'type':'bullet','text':html_text,'tech':is_tech(p),'level':level,'is_html':True})
                else:
                    what_is.append({'type':'para','text':html_text,'is_html':True})
        elif tag=='tbl' and in_wi:
            from docx.table import Table as DT
            tbl=DT(child,doc); ttype=identify_table(tbl)
            if ttype=='ibl_component':
                items=[{'type':'bullet','text':f'{clean(r.cells[0].text)}. {clean(r.cells[1].text)}','tech':False,'level':0}
                       for r in tbl.rows[1:] if clean(r.cells[0].text) and clean(r.cells[1].text)]
                what_is.append({'type':'bullet_group','items':items})
    data['what_is']=what_is

    # Key question
    for tbl in doc.tables:
        if tbl.rows and tbl.columns:
            text=clean(tbl.rows[0].cells[0].text)
            if text.lower().startswith('key question'):
                data['key_question_paras']=[clean(p.text) for p in tbl.rows[0].cells[0].paragraphs if clean(p.text)]
                break

    # LE section
    le_preamble=[]; phase_table_data=None; in_le=False; found_phase=False
    for child in body:
        tag=child.tag.split('}')[-1]
        if tag=='p':
            from docx.text.paragraph import Paragraph as DP
            p=DP(child,doc); text=para_text(p); style=para_style(p); tl=text.lower()
            if not in_le:
                if LE_START(tl,style): in_le=True; continue
            else:
                if LE_END(tl,style): break
                if found_phase: continue
                if not text and not has_image(p): continue
                if has_image(p):
                    src=extract_image_b64(p,docx_path)
                    if src: le_preamble.append({'type':'image','src':src,'caption':re.sub(r'^\.\s*','',text).strip()})
                    continue
                if 'Heading 3' in style:
                    le_preamble.append({'type':'subheading','text':para_html(p,rels),'is_html':True})
                    continue
                html_text=para_html(p,rels)
                if 'List Paragraph' in style:
                    level=get_bullet_level(p,abstract,num_to_abstract)
                    le_preamble.append({'type':'bullet','text':strip_tech(html_text) if is_tech(p) else html_text,'tech':is_tech(p),'level':level,'is_html':True})
                else:
                    le_preamble.append({'type':'para','text':html_text,'is_html':True})
        elif tag=='tbl' and in_le:
            from docx.table import Table as DT
            tbl=DT(child,doc); ttype=identify_table(tbl)
            if ttype=='key_question': continue
            if ttype=='phase' and not found_phase:
                phase_table_data=parse_phase_table(tbl,abstract,num_to_abstract,rels); found_phase=True
    data['le_preamble']=le_preamble
    if phase_table_data: data['phase_table']=phase_table_data

    # Diff section — free-flowing stream (bullets, images, tables in document order)
    diff_stream=[]; in_diff=False; last_img_idx=None
    for child in body:
        tag=child.tag.split('}')[-1]
        if tag=='p':
            from docx.text.paragraph import Paragraph as DP
            p=DP(child,doc); text=para_text(p); style=para_style(p); tl=text.lower()
            if not in_diff:
                if DIFF_START(tl,style): in_diff=True; continue
            else:
                if has_image(p):
                    src=extract_image_b64(p,docx_path)
                    if src:
                        caption=re.sub(r'^\.\s*','',text).strip()
                        diff_stream.append({'type':'image','src':src,'caption':caption})
                        last_img_idx=len(diff_stream)-1
                    continue
                if 'Caption' in style and last_img_idx is not None:
                    if not diff_stream[last_img_idx]['caption']:
                        diff_stream[last_img_idx]['caption']=re.sub(r'^\.\s*','',text).strip()
                    continue
                if not text: continue
                if 'Heading 3' in style:
                    diff_stream.append({'type':'subheading','text':para_html(p,rels),'is_html':True})
                    continue
                html_text=para_html(p,rels)
                if 'List Paragraph' in style:
                    level=get_bullet_level(p,abstract,num_to_abstract)
                    diff_stream.append({'type':'bullet','text':strip_tech(html_text) if is_tech(p) else html_text,'tech':is_tech(p),'level':level,'is_html':True})
                else:
                    diff_stream.append({'type':'para','text':html_text,'is_html':True})
        elif tag=='tbl' and in_diff:
            from docx.table import Table as DT
            tbl=DT(child,doc); ttype=identify_table(tbl)
            if ttype=='diff_ibl':
                diff_stream.append({'type':'table','table_type':'diff_ibl','data':parse_diff_table_ibl(tbl)})
            elif ttype=='diff_standard':
                diff_stream.append({'type':'table','table_type':'diff_standard','data':parse_diff_table_standard(tbl,abstract,num_to_abstract,rels)})
    data['diff_stream']=diff_stream
    return data

# ── build full panel HTML ──────────────────────────────────────────────────
def build_panel_html(key, data, meta):
    is_ibl=(key=='ibl')
    pt=data.get('phase_table')
    ht=has_tech(pt)

    # Download button
    dl=(f'<div class="panel-header">'
        f'<a class="download-btn" href="./{meta["file"]}" download>'
        f'<svg viewBox="0 0 16 16" fill="none" stroke="currentColor" stroke-width="1.8">'
        f'<path d="M8 2v8M5 7l3 3 3-3M2 12v1a1 1 0 001 1h10a1 1 0 001-1v-1"/></svg>'
        f'Download {meta["file"]}</a></div>')

    # Accordion 1
    wi_html=render_what_is_html(data.get('what_is',[]))
    a1=(f'<div class="accordion">'
        f'<button class="acc-btn" onclick="toggleAcc(\'{key}-what\')">'
        f'<span>What is {esc(meta["name"])}?</span><span class="acc-arrow">&#9660;</span></button>'
        f'<div class="acc-body" id="{key}-what">{wi_html}</div></div>')

    # Accordion 2
    le=render_key_question_html(data.get('key_question_paras'))
    le+=render_le_preamble_html(data.get('le_preamble',[]))

    toolbar=''
    if pt or ht:
        toolbar='<div class="phase-toolbar">'
        if pt:
            toolbar+=(f'<button class="ctrl-btn active" id="{key}-bt" onclick="setView(\'{key}\',\'table\')">&#9776; Table</button>'
                      f'<button class="ctrl-btn" id="{key}-bc" onclick="setView(\'{key}\',\'cards\')">&#9783; Cards</button>')
        if ht:
            toolbar+=(f'<label class="toggle-wrap" title="Show or hide technology suggestions">'
                      f'<input type="checkbox" id="{key}-btech" onchange="onTechToggle(\'{key}\')">'
                      f'<span class="toggle-track"></span>Show Tech</label>')
        if pt:
            toolbar+=f'<button class="ctrl-btn" id="{key}-bexp" onclick="toggleExpandAll(\'{key}\')">Expand all rows</button>'
        toolbar+='</div>'
    le+=toolbar

    if pt:
        tbl_html=render_phase_table_html(pt, is_ibl, key)
        cards_html=render_phase_cards_html(pt)
        le+=f'<div id="{key}-view" class="view-table tech-hidden">{tbl_html}{cards_html}</div>'

    a2=(f'<div class="accordion">'
        f'<button class="acc-btn" onclick="toggleAcc(\'{key}-le\')">'
        f'<span>An example of a teacher-facilitated LE</span><span class="acc-arrow">&#9660;</span></button>'
        f'<div class="acc-body" id="{key}-le">{le}</div></div>')

    # Accordion 3 — free-flowing diff stream
    first_phase=pt['rows'][0]['phase'] if pt and pt.get('rows') else 'Stage 1'
    diff=render_diff_stream_html(data.get('diff_stream',[]), first_phase)

    a3=(f'<div class="accordion">'
        f'<button class="acc-btn" onclick="toggleAcc(\'{key}-diff\')">'
        f'<span>Differentiating Instruction</span><span class="acc-arrow">&#9660;</span></button>'
        f'<div class="acc-body" id="{key}-diff">{diff}</div></div>')

    return dl+a1+a2+a3

# ── main ───────────────────────────────────────────────────────────────────
APPROACH_META = {
    'pbl': {'name':'Problem-Based Learning',          'file':'PBL.docx'},
    'ibl': {'name':'Inquiry-Based Learning',           'file':'IBL.docx'},
    'cbl': {'name':'Concept-Based Learning',           'file':'CBL.docx'},
    'ssi': {'name':'Socio-Scientific Issues-based Learning', 'file':'SSI.docx'},
}

def main():
    docs = {'pbl':SCRIPT_DIR/'PBL.docx','ibl':SCRIPT_DIR/'IBL.docx',
            'cbl':SCRIPT_DIR/'CBL.docx','ssi':SCRIPT_DIR/'SSI.docx'}
    panels = {}
    for key, path in docs.items():
        if not path.exists(): print(f'WARNING: {path} not found'); panels[key]=''; continue
        print(f'Parsing {path.name}...')
        data = parse_doc(str(path), key)
        panels[key] = build_panel_html(key, data, APPROACH_META[key])
        print(f'  Done: {key}')

    template_path = SCRIPT_DIR/'template.html'
    output_path   = SCRIPT_DIR/'pedagogy-hub.html'
    if not template_path.exists(): print(f'ERROR: template.html not found'); return
    template = template_path.read_text(encoding='utf-8')
    for key, html in panels.items():
        template = template.replace(f'__{key.upper()}_PANEL__', html)
    output_path.write_text(template, encoding='utf-8')
    print(f'\nOutput written to {output_path}')

if __name__ == '__main__':
    main()
